spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  config:
    import:
      - optional:classpath:districts.yml
      - optional:file:./config/districts.yml
seoul:
  api:
    key: 6f4a495a43706a7338334b7843536e
    base-url: http://openapi.seoul.go.kr:8088

modelrestaurant:
  districts: ydp,yangcheon,ddm,dongjak