spring:
  profiles:
    active: prod
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true


custom:
  jwt:
    secret-key: ${JWT_SECRET_KEY}      
    access-token:
      expire-time: 1800000              # 30분 (ms)
    refresh-token:
      expire-time: 604800000            # 7일 (ms)

springdoc:
  default-produces-media-type: application/json