spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
